language: node_js

sudo: false

node_js: 6

env:
  - CXX=g++-6 CC=gcc-6

script: npm run ci

git:
  depth: 10

branches:
  only:
    - master

notifications:
  email:
    on_success: never
    on_failure: change

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-6
    - g++-6
