language: node_js

sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "0.12"
  - "4.0"

git:
  depth: 10

branches:
  only:
    - master

env:
  - CC=clang CXX=clang++ npm_config_clang=1
