environment:
  nodejs_version: "6"

platform: x64

image: Visual Studio 2015

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init.exe -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

build: off

on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
