environment:
  nodejs_version: "6"

install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Start-FileDownload "https://static.rust-lang.org/rustup/dist/i686-pc-windows-gnu/rustup-init.exe"
  - rustup-init.exe -y
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run ci

build: off
